//
//  SignUpPasswordViewController.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPasswordDisplayLogic: class
{
  
}

class SignUpPasswordViewController: UIViewController, SignUpPasswordDisplayLogic, UIScrollViewDelegate
{
  
  var router: SignUpPasswordRouter?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let router = SignUpPasswordRouter()
    viewController.router = router
    router.viewController = viewController
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setup()
    newPasswordTextField.becomeFirstResponder()
  }
    
    static func getInstance() -> SignUpPasswordViewController {
        let storyboard = UIStoryboard(name: SIGNUP_PASSWORD_NAME, bundle: nil)
        return (storyboard.instantiateViewController(withIdentifier: SIGNUP_PASSWORD_STORYBOARD_ID) as! SignUpPasswordViewController)
    }
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    @IBAction func nextbuttonPressed(_ sender: UIBarButtonItem) {
    }
    
    @IBOutlet weak var newPasswordTextField: UITextField!
    
    @IBOutlet weak var confirmPasswordTextField: UITextField!
}
