//
//  LoginViewController.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{

}

class LoginViewController: UIViewController, LoginDisplayLogic, UIScrollViewDelegate
{
  var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
  
    //MARK: Outlets & Actions
    
    @IBOutlet weak var BackgroundScrollView: UIScrollView!
    
    @IBAction func LoginButtonPressed(_ sender: UIBarButtonItem) {
    }
    
    @IBAction func SignUpButtonPressed(_ sender: UIButton) {
        router?.navigateToSignUp()
    }
    @IBOutlet weak var usernameTextField: UITextField!
    
    @IBOutlet weak var passwordTextField: UITextField!
    
    
    // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginInteractor()
    let presenter = LoginPresenter()
    let router = LoginRouter()
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  override func viewDidLoad()
  {
    setup()
    super.viewDidLoad()
    BackgroundScrollView.delegate = self
    usernameTextField.becomeFirstResponder()
    self.navigationController?.navigationBar.isHidden = false
  }
    
//    func viewWillDisappear(_ animated: Bool) {
//        self
//    }

    static func getInstance() -> LoginViewController {
        let storyboard = UIStoryboard(name: LOGIN_STORYBOARD_NAME, bundle: nil)
        return (storyboard.instantiateViewController(withIdentifier: LOGIN_STORYBOARD_ID) as! LoginViewController)
    }

}
