//
//  WelcomeRouter.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic
{
    func navigateToLoginScene()
    func navigateToSignUpScene()
}

class WelcomeRouter: WelcomeRoutingLogic{
    weak var viewController : WelcomeViewController?
    
    //MARK: Actions & Outlets
    
    
    
    //MARK : Navigaiton
    func navigateToSignUpScene() {
        let SignVC = SignUpViewController.getInstance()
        viewController?.navigationController?.pushViewController(SignVC, animated: true)
    }
    
    func navigateToLoginScene() {
        let loginVC = LoginViewController.getInstance()
        viewController?.navigationController?.pushViewController(loginVC, animated: true)
        
    }
}
