//
//  SignUpViewController.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpDisplayLogic: class
{

}

class SignUpViewController: UIViewController, SignUpDisplayLogic, UIScrollViewDelegate, UINavigationControllerDelegate
{
  var router: SignUpRouter?

  // MARK: Object lifecycle
  
    //MARK: Outlets
    
    @IBAction func LoginButtonPressed(_ sender: Any) {
        router?.navigatetoLoginScreen()
    }
    
    @IBAction func NextButtonPressed(_ sender: UIBarButtonItem) {
        router?.navigatetoUserNameScreen()
    }
    @IBOutlet weak var firstnameTextField: UITextField!
    
    @IBOutlet weak var lastnameTextField: UITextField!
    
  //MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let presenter = SignUpPresenter()
    let router = SignUpRouter()
    viewController.router = router
    presenter.viewController = viewController
    router.viewController = viewController
  }
  
  // MARK: Routing
  
  
  // MARK: View lifecycle
  
    override func viewDidLoad()
    {
      setup()
      super.viewDidLoad()
      firstnameTextField.becomeFirstResponder()
      self.navigationController?.navigationBar.isHidden = false
    }
  
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
    }
    
    static func getInstance() -> SignUpViewController {
        let storyboard = UIStoryboard(name: SIGNUP_STORYBOARD_NAME, bundle: nil)
        return (storyboard.instantiateViewController(withIdentifier: SIGNUP_STORYBOARD_ID)as! SignUpViewController)
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!

}
