//
//  SignUpUserNameRouter.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpUserNameRoutingLogic
{
  func navigatetoSignUpPasswordScene()
}

class SignUpUserNameRouter: NSObject, SignUpUserNameRoutingLogic
{
  weak var viewController: SignUpUserNameViewController?
  
    //MARK: Navigating
    
    func navigatetoSignUpPasswordScene() {
        let SignUpPass = SignUpPasswordViewController.getInstance()
        viewController?.navigationController?.pushViewController(SignUpPass, animated: true)
    }
}
