//
//  SignUpUserNameViewController.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpUserNameDisplayLogic: class
{
 
}

class SignUpUserNameViewController: UIViewController, SignUpUserNameDisplayLogic, UIScrollViewDelegate
{
    
    //MARK: Actions & Outlets

    @IBAction func NextButtonPressed(_ sender: UIBarButtonItem) {
        router?.navigatetoSignUpPasswordScene()
    }
    @IBOutlet weak var usernameTextField: UITextField!
    
    
  var router: SignUpUserNameRouter?

  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let router = SignUpUserNameRouter()
    viewController.router = router
    router.viewController = viewController
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setup()
    usernameTextField.becomeFirstResponder()
  }
    
    static func getInstance() -> SignUpUserNameViewController {
    let storyboard = UIStoryboard(name: SIGNUP_USERNAME_STORYBOARD_NAME, bundle: nil)
        return (storyboard.instantiateViewController(withIdentifier: SIGNUP_USERNAME_STORYBOARD_ID) as! SignUpUserNameViewController)
    }
}
