//
//  SignUpRouter.swift
//  LoginScreen
//
//  Created by Pavan Gudur on 11/19/18.
//  Copyright (c) 2018 Pavan Gudur. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func navigatetoLoginScreen()
}

class SignUpRouter: NSObject, SignUpRoutingLogic{
    weak var viewController: SignUpViewController?
    
        //MARK : Navigaiton
    
    func navigatetoLoginScreen() {
        let loginVC = LoginViewController.getInstance()
        viewController?.navigationController?.pushViewController(loginVC, animated: true)
    }
  
  
}
